# Generated by Django 6.0.3 on 2026-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='blog',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
